[package]
name = "aoc19"
description = "Advent of Code solutions written in Rust"
version = "0.1.0"
authors = ["macph <macph@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
